// randomImage: `https://picsum.photos/1440/900?random=${getRandomInt(1000)}`,
// randomImage01: `https://picsum.photos/1440/900?random=${getRandomInt(1000)}`,
// randomImage02: `https://picsum.photos/1440/900?random=${getRandomInt(1000)}`,
// randomImage03: `https://picsum.photos/1440/900?random=${getRandomInt(1000)}`,
// randomImage04: `https://picsum.photos/1440/900?random=${getRandomInt(1000)}`,
import { RiLayoutMasonryLine } from "react-icons/ri";
import { RiCheckboxMultipleBlankFill } from "react-icons/ri";
import { IoApertureOutline } from "react-icons/io5";
import { MdFormatAlignCenter } from "react-icons/md";

import { getRandomImage } from "./getRandomImages";

interface ArtistSkillProps {
  id: number;
  icon: React.ComponentType; // React 컴포넌트 타입 (React Icons 포함)
  skill: string;
}

export interface ArtistDataProps {
  id: number;
  nickname: string;
  last_name: string;
  email: string;
  city: string;
  street_address: string;
  introduction: string;
  randomImage: string;
  randomImage01: string;
  randomImage02: string;
  randomImage03: string;
  randomImage04: string;
  hash?: string[];
  url?: string;
  skills: ArtistSkillProps[];
  isWishlisted?: boolean;
}

export const artistSkills:ArtistSkillProps[] = [
  { id: 1, icon: RiLayoutMasonryLine, skill: "디지털" },
  { id: 2, icon: RiCheckboxMultipleBlankFill, skill: "설치" },
  { id: 3, icon: IoApertureOutline, skill: "다중매체" },
  { id: 4, icon: MdFormatAlignCenter, skill: "추상" },
  // { icon: PiTriangleDashed, skill: "구상" },
  // { icon: PiTriangleDashed, skill: "페인팅" },
  // { icon: PiTriangleDashed, skill: "전통" },
  // { icon: PiTriangleDashed, skill: "도예" },
  // { icon: PiTriangleDashed, skill: "금속" },
  // { icon: PiTriangleDashed, skill: "목공" },
  // { icon: PiTriangleDashed, skill: "환경" },
  // { icon: PiTriangleDashed, skill: "조각" },
  // { icon: PiTriangleDashed, skill: "사회" },
];

// function getRandomSkills(): string[] {
//   let result: string[] = [];
//   while (result.length < 4) {
//     const randomSkills = skills[Math.floor(Math.random() * skills.length)];
//     if (!result.includes(randomSkills)) {
//       result.push(randomSkills);
//     }
//   }
//   return result;
// }
//데이터 최하단에 forEach로 할당

const artistdata: ArtistDataProps[] = [
  {
    id: 1,
    nickname: "Lydon",
    last_name: "Sleite",
    email: "lsleite0@ucsd.edu",
    city: "Gueset",
    street_address: "78609 Main Parkway",
    introduction:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 2,
    nickname: "Jen",
    last_name: "Dowglass",
    email: "jdowglass1@macromedia.com",
    city: "Metallostroy",
    street_address: "6935 Farragut Lane",
    introduction:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 3,
    nickname: "Remus",
    last_name: "Lammerich",
    email: "rlammerich2@walmart.com",
    city: "Rokytne",
    street_address: "25376 Shoshone Terrace",
    introduction:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 4,
    nickname: "Edi",
    last_name: "Fairney",
    email: "efairney3@cpanel.net",
    city: "Xuri",
    street_address: "77 Ridgeway Lane",
    introduction:
      "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 5,
    nickname: "Tabitha",
    last_name: "Hadlee",
    email: "thadlee4@bbb.org",
    city: "Carcassonne",
    street_address: "63 Meadow Valley Trail",
    introduction:
      "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 6,
    nickname: "Kristofer",
    last_name: "O'Breen",
    email: "kobreen5@godaddy.com",
    city: "Al Ghuwayrīyah",
    street_address: "1348 Mosinee Hill",
    introduction:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 7,
    nickname: "Callean",
    last_name: "Obispo",
    email: "cobispo6@constantcontact.com",
    city: "Cabo Frio",
    street_address: "2 Washington Place",
    introduction:
      "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 8,
    nickname: "Molli",
    last_name: "Blenkinsopp",
    email: "mblenkinsopp7@google.ca",
    city: "Kalianyar Selatan",
    street_address: "4 Delladonna Drive",
    introduction:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 9,
    nickname: "Roseline",
    last_name: "Brann",
    email: "rbrann8@ucla.edu",
    city: "Chengnan",
    street_address: "51 Scofield Place",
    introduction:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 10,
    nickname: "Susie",
    last_name: "Vittore",
    email: "svittore9@uol.com.br",
    city: "Hennenman",
    street_address: "53 Lindbergh Terrace",
    introduction:
      "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 11,
    nickname: "Etienne",
    last_name: "Vaines",
    email: "evainesa@nytimes.com",
    city: "R S",
    street_address: "02598 Basil Trail",
    introduction:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 12,
    nickname: "Maxie",
    last_name: "Pinks",
    email: "mpinksb@paypal.com",
    city: "San Antonio",
    street_address: "1032 Myrtle Court",
    introduction:
      "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 13,
    nickname: "Chloris",
    last_name: "Lehr",
    email: "clehrc@blogtalkradio.com",
    city: "Napu",
    street_address: "73575 Lien Terrace",
    introduction:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 14,
    nickname: "Tiertza",
    last_name: "Francklyn",
    email: "tfrancklynd@ebay.co.uk",
    city: "San Justo",
    street_address: "9 Farmco Parkway",
    introduction:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 15,
    nickname: "Sondra",
    last_name: "Everill",
    email: "severille@about.com",
    city: "Plavy",
    street_address: "1 Village Green Hill",
    introduction:
      "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 16,
    nickname: "Vanya",
    last_name: "Caustick",
    email: "vcaustickf@go.com",
    city: "Pavlovskaya",
    street_address: "0 Vera Alley",
    introduction:
      "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 17,
    nickname: "Dalis",
    last_name: "Gunda",
    email: "dgundag@clickbank.net",
    city: "Łagów",
    street_address: "27 Spaight Point",
    introduction:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 18,
    nickname: "Sylvia",
    last_name: "Phippen",
    email: "sphippenh@cloudflare.com",
    city: "Pasembon",
    street_address: "8859 Miller Crossing",
    introduction:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 19,
    nickname: "Bernete",
    last_name: "Furneaux",
    email: "bfurneauxi@youku.com",
    city: "Pojok",
    street_address: "7 Sunfield Place",
    introduction:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 20,
    nickname: "Terrel",
    last_name: "Blaxton",
    email: "tblaxtonj@wordpress.com",
    city: "Deskle",
    street_address: "5 Declaration Avenue",
    introduction:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 21,
    nickname: "Verile",
    last_name: "Georgi",
    email: "vgeorgik@1und1.de",
    city: "Laspezia",
    street_address: "3465 Walton Circle",
    introduction: "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 22,
    nickname: "Hyacinthe",
    last_name: "Pietzker",
    email: "hpietzkerl@weather.com",
    city: "Predavac",
    street_address: "7386 Ridgeview Point",
    introduction:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 23,
    nickname: "Vernon",
    last_name: "Hovie",
    email: "vhoviem@feedburner.com",
    city: "Taraban Timur",
    street_address: "58086 Cambridge Pass",
    introduction:
      "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 24,
    nickname: "Kurtis",
    last_name: "Syne",
    email: "ksynen@ehow.com",
    city: "Nong Hin",
    street_address: "0425 Beilfuss Junction",
    introduction:
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 25,
    nickname: "Hermia",
    last_name: "Fraschini",
    email: "hfraschinio@deviantart.com",
    city: "Port Barton",
    street_address: "064 Loomis Alley",
    introduction:
      "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 26,
    nickname: "Nathaniel",
    last_name: "O'Shevlan",
    email: "noshevlanp@studiopress.com",
    city: "Cilegong",
    street_address: "1 Bunker Hill Pass",
    introduction:
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 27,
    nickname: "Bertie",
    last_name: "Drust",
    email: "bdrustq@myspace.com",
    city: "Wukou",
    street_address: "17543 Darwin Terrace",
    introduction:
      "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 28,
    nickname: "Kandace",
    last_name: "Mithun",
    email: "kmithunr@oakley.com",
    city: "Paratinga",
    street_address: "1902 Banding Road",
    introduction:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 29,
    nickname: "Adria",
    last_name: "Hamp",
    email: "ahamps@ftc.gov",
    city: "Paris 12",
    street_address: "03631 Cascade Junction",
    introduction:
      "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 30,
    nickname: "Prent",
    last_name: "Lehenmann",
    email: "plehenmannt@hud.gov",
    city: "Sanjinquan",
    street_address: "488 Claremont Drive",
    introduction:
      "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 31,
    nickname: "Christel",
    last_name: "De Domenicis",
    email: "cdedomenicisu@whitehouse.gov",
    city: "Wassa-Akropong",
    street_address: "0 Ryan Crossing",
    introduction:
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 32,
    nickname: "Carlynne",
    last_name: "Baud",
    email: "cbaudv@taobao.com",
    city: "Nova Lima",
    street_address: "82053 Dovetail Alley",
    introduction:
      "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 33,
    nickname: "Broddie",
    last_name: "Feaveer",
    email: "bfeaveerw@cbslocal.com",
    city: "Rantaupanjangkiri",
    street_address: "356 Sauthoff Trail",
    introduction: "Fusce consequat. Nulla nisl. Nunc nisl.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 34,
    nickname: "Lexy",
    last_name: "Dellit",
    email: "ldellitx@apple.com",
    city: "Taokeng",
    street_address: "01247 Colorado Way",
    introduction:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 35,
    nickname: "Chastity",
    last_name: "Charley",
    email: "ccharleyy@i2i.jp",
    city: "Monte Francisco",
    street_address: "94089 Harbort Court",
    introduction:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 36,
    nickname: "Lesly",
    last_name: "Dupree",
    email: "ldupreez@github.com",
    city: "Firenze",
    street_address: "17531 Ryan Hill",
    introduction:
      "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 37,
    nickname: "Brandea",
    last_name: "Shipley",
    email: "bshipley10@hc360.com",
    city: "Wengtian",
    street_address: "91 Donald Park",
    introduction:
      "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 38,
    nickname: "Whitney",
    last_name: "Grierson",
    email: "wgrierson11@howstuffworks.com",
    city: "Walakeri",
    street_address: "4 Eagan Drive",
    introduction:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 39,
    nickname: "Randolf",
    last_name: "Albrook",
    email: "ralbrook12@smh.com.au",
    city: "Ibara",
    street_address: "65 Granby Parkway",
    introduction:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 40,
    nickname: "Ynez",
    last_name: "Fice",
    email: "yfice13@fotki.com",
    city: "Tianzhuang",
    street_address: "77444 Green Parkway",
    introduction:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 41,
    nickname: "Bentlee",
    last_name: "Rushmere",
    email: "brushmere14@home.pl",
    city: "Zliten",
    street_address: "599 Bowman Trail",
    introduction:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 42,
    nickname: "Caz",
    last_name: "Craythorn",
    email: "ccraythorn15@ed.gov",
    city: "Louisville",
    street_address: "0674 Thompson Parkway",
    introduction:
      "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 43,
    nickname: "Kareem",
    last_name: "Scapelhorn",
    email: "kscapelhorn16@slideshare.net",
    city: "Zitong",
    street_address: "1 Fordem Road",
    introduction: "Fusce consequat. Nulla nisl. Nunc nisl.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 44,
    nickname: "Martelle",
    last_name: "Barti",
    email: "mbarti17@vistaprint.com",
    city: "Victoria",
    street_address: "7 Manitowish Avenue",
    introduction:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 45,
    nickname: "Karel",
    last_name: "Keat",
    email: "kkeat18@mtv.com",
    city: "Želešice",
    street_address: "4 Kennedy Center",
    introduction:
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 46,
    nickname: "Hercules",
    last_name: "Leeds",
    email: "hleeds19@eventbrite.com",
    city: "Bhāi Pheru",
    street_address: "401 Fisk Place",
    introduction:
      "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 47,
    nickname: "Bili",
    last_name: "Hallifax",
    email: "bhallifax1a@weibo.com",
    city: "Ad Darbāsīyah",
    street_address: "4 Bellgrove Road",
    introduction:
      "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 48,
    nickname: "Emile",
    last_name: "Wollaston",
    email: "ewollaston1b@narod.ru",
    city: "Castlerea",
    street_address: "7710 Northridge Park",
    introduction: "Sed ante. Vivamus tortor. Duis mattis egestas metus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 49,
    nickname: "Cherrita",
    last_name: "Need",
    email: "cneed1c@shareasale.com",
    city: "Balucuc",
    street_address: "99306 Florence Lane",
    introduction:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 50,
    nickname: "Caressa",
    last_name: "Jenken",
    email: "cjenken1d@auda.org.au",
    city: "Árgos",
    street_address: "4708 Hanson Center",
    introduction:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 51,
    nickname: "Joline",
    last_name: "Chardin",
    email: "jchardin1e@fotki.com",
    city: "Madimba",
    street_address: "57701 Homewood Circle",
    introduction:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 52,
    nickname: "Jeannine",
    last_name: "Bortolussi",
    email: "jbortolussi1f@symantec.com",
    city: "Rožďalovice",
    street_address: "422 Pepper Wood Terrace",
    introduction:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 53,
    nickname: "Demetre",
    last_name: "Letterese",
    email: "dletterese1g@devhub.com",
    city: "Marne-la-Vallée",
    street_address: "9 Oxford Pass",
    introduction:
      "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 54,
    nickname: "Doy",
    last_name: "Mintrim",
    email: "dmintrim1h@dion.ne.jp",
    city: "James Craik",
    street_address: "6352 Swallow Parkway",
    introduction:
      "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 55,
    nickname: "Lurette",
    last_name: "Simonson",
    email: "lsimonson1i@blinklist.com",
    city: "Dayu",
    street_address: "2070 Tennessee Parkway",
    introduction:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 56,
    nickname: "Jules",
    last_name: "Tuffley",
    email: "jtuffley1j@omniture.com",
    city: "Arauca",
    street_address: "50886 Moulton Terrace",
    introduction:
      "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 57,
    nickname: "Isadora",
    last_name: "Whiff",
    email: "iwhiff1k@ucsd.edu",
    city: "Davyd-Haradok",
    street_address: "46 Burrows Terrace",
    introduction:
      "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 58,
    nickname: "Nari",
    last_name: "Matveichev",
    email: "nmatveichev1l@artisteer.com",
    city: "Jaunpiebalga",
    street_address: "55273 Shasta Park",
    introduction:
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 59,
    nickname: "Valentine",
    last_name: "Itzkovitch",
    email: "vitzkovitch1m@yolasite.com",
    city: "Xinning",
    street_address: "536 Ramsey Hill",
    introduction: "Sed ante. Vivamus tortor. Duis mattis egestas metus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 60,
    nickname: "Rita",
    last_name: "Brinkley",
    email: "rbrinkley1n@hubpages.com",
    city: "Zmiennica",
    street_address: "1893 Coleman Plaza",
    introduction:
      "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 61,
    nickname: "Ashlan",
    last_name: "Arondel",
    email: "aarondel1o@guardian.co.uk",
    city: "Västerås",
    street_address: "7557 Drewry Place",
    introduction:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 62,
    nickname: "Neville",
    last_name: "Von Der Empten",
    email: "nvonderempten1p@spiegel.de",
    city: "Zyablikovo",
    street_address: "60 Milwaukee Circle",
    introduction:
      "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 63,
    nickname: "Bobine",
    last_name: "Rantoull",
    email: "brantoull1q@yolasite.com",
    city: "Solna",
    street_address: "8 Alpine Alley",
    introduction:
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 64,
    nickname: "Anatollo",
    last_name: "Branson",
    email: "abranson1r@ask.com",
    city: "Had Kourt",
    street_address: "0 Magdeline Place",
    introduction: "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 65,
    nickname: "Bianka",
    last_name: "Buesden",
    email: "bbuesden1s@technorati.com",
    city: "El Limon",
    street_address: "38 Trailsway Park",
    introduction:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 66,
    nickname: "Leelah",
    last_name: "Harbach",
    email: "lharbach1t@omniture.com",
    city: "Batiano",
    street_address: "28 Bellgrove Street",
    introduction:
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 67,
    nickname: "Emylee",
    last_name: "Sundin",
    email: "esundin1u@bluehost.com",
    city: "Biito",
    street_address: "795 Derek Avenue",
    introduction:
      "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 68,
    nickname: "Ole",
    last_name: "Sanders",
    email: "osanders1v@dmoz.org",
    city: "G‘azalkent",
    street_address: "73027 Dunning Plaza",
    introduction:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 69,
    nickname: "Ivie",
    last_name: "Frizell",
    email: "ifrizell1w@vk.com",
    city: "Nunutba",
    street_address: "0246 Browning Point",
    introduction:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 70,
    nickname: "Travis",
    last_name: "Brannigan",
    email: "tbrannigan1x@marriott.com",
    city: "Shiguai",
    street_address: "05 Crowley Junction",
    introduction:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 71,
    nickname: "Beth",
    last_name: "Lezemore",
    email: "blezemore1y@phpbb.com",
    city: "Wansheng",
    street_address: "075 Stang Trail",
    introduction:
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 72,
    nickname: "Rodrick",
    last_name: "Goodwin",
    email: "rgoodwin1z@ebay.com",
    city: "Valdemarsvik",
    street_address: "99 Di Loreto Avenue",
    introduction:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 73,
    nickname: "Betti",
    last_name: "Waters",
    email: "bwaters20@ucla.edu",
    city: "Pingshi",
    street_address: "20 Esch Center",
    introduction:
      "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 74,
    nickname: "Laina",
    last_name: "Fairlem",
    email: "lfairlem21@comsenz.com",
    city: "Uchiza",
    street_address: "12036 Karstens Pass",
    introduction:
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 75,
    nickname: "Shermy",
    last_name: "Ruprechter",
    email: "sruprechter22@accuweather.com",
    city: "Orléans",
    street_address: "716 Clarendon Pass",
    introduction:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 76,
    nickname: "Natalya",
    last_name: "Biasotti",
    email: "nbiasotti23@youtu.be",
    city: "Mandalay",
    street_address: "9 Golden Leaf Court",
    introduction:
      "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 77,
    nickname: "Auguste",
    last_name: "Hellen",
    email: "ahellen24@odnoklassniki.ru",
    city: "Sangkalputung",
    street_address: "657 Raven Place",
    introduction:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 78,
    nickname: "Kimball",
    last_name: "Fazzioli",
    email: "kfazzioli25@nymag.com",
    city: "Volosovo",
    street_address: "7661 Monterey Point",
    introduction:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 79,
    nickname: "Miner",
    last_name: "Trevance",
    email: "mtrevance26@twitter.com",
    city: "Xiaojia",
    street_address: "8 Mayfield Drive",
    introduction:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 80,
    nickname: "Brandise",
    last_name: "Mereweather",
    email: "bmereweather27@prweb.com",
    city: "Ćmielów",
    street_address: "800 Aberg Alley",
    introduction:
      "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 81,
    nickname: "Terrill",
    last_name: "Riolfo",
    email: "triolfo28@baidu.com",
    city: "Xinsheng",
    street_address: "6929 Atwood Lane",
    introduction:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 82,
    nickname: "Hedda",
    last_name: "Akred",
    email: "hakred29@blinklist.com",
    city: "Pawa",
    street_address: "7845 Carey Park",
    introduction:
      "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 83,
    nickname: "Any",
    last_name: "Cowie",
    email: "acowie2a@home.pl",
    city: "El Puerto",
    street_address: "6784 Doe Crossing Point",
    introduction:
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 84,
    nickname: "Felicdad",
    last_name: "Pauli",
    email: "fpauli2b@forbes.com",
    city: "Casma",
    street_address: "62 Hudson Court",
    introduction:
      "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 85,
    nickname: "Mylo",
    last_name: "Vidyapin",
    email: "mvidyapin2c@hp.com",
    city: "Abejorral",
    street_address: "63 Golf Terrace",
    introduction:
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 86,
    nickname: "Yoshiko",
    last_name: "Ingre",
    email: "yingre2d@usda.gov",
    city: "Rosario",
    street_address: "21899 Talmadge Point",
    introduction:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 87,
    nickname: "Jasmin",
    last_name: "Marzelle",
    email: "jmarzelle2e@thetimes.co.uk",
    city: "Krajan Dua Padomasan",
    street_address: "2 Barnett Alley",
    introduction:
      "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 88,
    nickname: "Iris",
    last_name: "Truran",
    email: "itruran2f@google.it",
    city: "Kolomanu",
    street_address: "1 Canary Avenue",
    introduction:
      "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 89,
    nickname: "Emalia",
    last_name: "Tebbett",
    email: "etebbett2g@wufoo.com",
    city: "Jobabo",
    street_address: "65319 Troy Court",
    introduction:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 90,
    nickname: "Brent",
    last_name: "Voice",
    email: "bvoice2h@tmall.com",
    city: "Krajan Karangsari",
    street_address: "757 Helena Hill",
    introduction:
      "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 91,
    nickname: "Lucretia",
    last_name: "Steaning",
    email: "lsteaning2i@tripod.com",
    city: "Järfälla",
    street_address: "938 Anthes Plaza",
    introduction:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 92,
    nickname: "Meaghan",
    last_name: "Orkney",
    email: "morkney2j@google.fr",
    city: "Mundão",
    street_address: "1 International Point",
    introduction:
      "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 93,
    nickname: "Oralee",
    last_name: "Snaden",
    email: "osnaden2k@engadget.com",
    city: "Néa Róda",
    street_address: "9627 Eagan Alley",
    introduction:
      "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 94,
    nickname: "Delphinia",
    last_name: "Fraschetti",
    email: "dfraschetti2l@gnu.org",
    city: "Mora",
    street_address: "53 Arrowood Crossing",
    introduction:
      "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 95,
    nickname: "Lari",
    last_name: "Sainte Paul",
    email: "lsaintepaul2m@rakuten.co.jp",
    city: "Pārūn",
    street_address: "2 Chinook Alley",
    introduction:
      "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 96,
    nickname: "Nelly",
    last_name: "Gibbs",
    email: "ngibbs2n@ifeng.com",
    city: "Massakory",
    street_address: "89826 Northland Avenue",
    introduction:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 97,
    nickname: "Philomena",
    last_name: "Thurlow",
    email: "pthurlow2o@ezinearticles.com",
    city: "Pingqiao",
    street_address: "74395 Algoma Avenue",
    introduction:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 98,
    nickname: "Lissa",
    last_name: "Glyssanne",
    email: "lglyssanne2p@dyndns.org",
    city: "Kowary",
    street_address: "948 Vermont Hill",
    introduction: "In congue. Etiam justo. Etiam pretium iaculis justo.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 99,
    nickname: "Daren",
    last_name: "Blakeborough",
    email: "dblakeborough2q@sogou.com",
    city: "Longtian",
    street_address: "036 Everett Drive",
    introduction:
      "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
  {
    id: 100,
    nickname: "Lynnette",
    last_name: "Piesing",
    email: "lpiesing2r@reddit.com",
    city: "Lubenec",
    street_address: "11 Scott Way",
    introduction:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    randomImage: getRandomImage(),
    randomImage01: getRandomImage(),
    randomImage02: getRandomImage(),
    randomImage03: getRandomImage(),
    randomImage04: getRandomImage(),
    skills: artistSkills,
  },
];

// artistdata.forEach((artist) => {
//   artist.hash = getRandomSkills();
// });

export default artistdata;
