import { imagesArr } from "./getRandomImages";

interface ArtistSkillProps {
  id: number;
  iconName: string;
  skill: string;
}

export interface ArtistDataProps {
  id: number;
  nickname: string;
  last_name: string;
  email: string;
  city: string;
  street_address: string;
  introduction: string;
  mainImage: string;
  randomImage01: string;
  randomImage02: string;
  randomImage03: string;
  randomImage04: string;
  url?: string;
  skills: { id: number; iconName: string; skill: string }[];
  isWishlisted?: boolean;
}

export const artistSkills: ArtistSkillProps[] = [
  { id: 1, iconName: "RiLayoutMasonryLine", skill: "디지털" },
  { id: 2, iconName: "RiCheckboxMultipleBlankFill", skill: "설치" },
  { id: 3, iconName: "IoApertureOutline", skill: "다중매체" },
  { id: 4, iconName: "FaEnvira", skill: "환경" },
  { id: 5, iconName: "IoShareSocialOutline", skill: "사회" },
  { id: 6, iconName: "RiPaintFill", skill: "페인팅" },
  { id: 7, iconName: "MdPieChart", skill: "조각" },
  { id: 8, iconName: "FaCircleNotch", skill: "도예" },
  { id: 9, iconName: "FaGripfire", skill: "금속" },
  { id: 10, iconName: "LuTreePine", skill: "목공" },
];

export const getSkillsByIds = (skillIds: number[] = []): ArtistSkillProps[] => {
  if (!Array.isArray(skillIds)) {
    console.error("Invalid skillIds:", skillIds);
    return []; // skillIds가 배열이 아니면 빈 배열 반환
  }
  return artistSkills.filter((skill) => skillIds.includes(skill.id));
};

export const artistData: ArtistDataProps[] = [
  {
    id: 1,
    nickname: "Lydon",
    last_name: "Sleite",
    email: "lsleite0@ucsd.edu",
    city: "Gueset",
    street_address: "78609 Main Parkway",
    introduction:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    mainImage: imagesArr[0],
    randomImage01: imagesArr[1],
    randomImage02: imagesArr[2],
    randomImage03: imagesArr[3],
    randomImage04: imagesArr[4],
    skills: getSkillsByIds([1, 2, 5, 10]),
  },
  {
    id: 2,
    nickname: "Jen",
    last_name: "Dowglass",
    email: "jdowglass1@macromedia.com",
    city: "Metallostroy",
    street_address: "6935 Farragut Lane",
    introduction:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    mainImage: imagesArr[1],
    randomImage01: imagesArr[2],
    randomImage02: imagesArr[3],
    randomImage03: imagesArr[4],
    randomImage04: imagesArr[5],
    skills: getSkillsByIds([3, 6, 7, 9]),
  },
  {
    id: 3,
    nickname: "Remus",
    last_name: "Lammerich",
    email: "rlammerich2@walmart.com",
    city: "Rokytne",
    street_address: "25376 Shoshone Terrace",
    introduction:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    mainImage: imagesArr[2],
    randomImage01: imagesArr[3],
    randomImage02: imagesArr[4],
    randomImage03: imagesArr[5],
    randomImage04: imagesArr[6],
    skills: getSkillsByIds([6, 7, 8, 9]),
  },
  {
    id: 4,
    nickname: "Edi",
    last_name: "Fairney",
    email: "efairney3@cpanel.net",
    city: "Xuri",
    street_address: "77 Ridgeway Lane",
    introduction:
      "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    mainImage: imagesArr[3],
    randomImage01: imagesArr[4],
    randomImage02: imagesArr[5],
    randomImage03: imagesArr[6],
    randomImage04: imagesArr[7],
    skills: getSkillsByIds([4, 5, 8, 9]),
  },
  {
    id: 5,
    nickname: "Tabitha",
    last_name: "Hadlee",
    email: "thadlee4@bbb.org",
    city: "Carcassonne",
    street_address: "63 Meadow Valley Trail",
    introduction:
      "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
    mainImage: imagesArr[4],
    randomImage01: imagesArr[5],
    randomImage02: imagesArr[6],
    randomImage03: imagesArr[7],
    randomImage04: imagesArr[8],
    skills: getSkillsByIds([2, 5, 6, 8, 10]),
  },
  {
    id: 6,
    nickname: "Kristofer",
    last_name: "O'Breen",
    email: "kobreen5@godaddy.com",
    city: "Al Ghuwayrīyah",
    street_address: "1348 Mosinee Hill",
    introduction:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    mainImage: imagesArr[5],
    randomImage01: imagesArr[6],
    randomImage02: imagesArr[7],
    randomImage03: imagesArr[8],
    randomImage04: imagesArr[9],
    skills: getSkillsByIds([3, 8, 9, 10]),
  },
  {
    id: 7,
    nickname: "Callean",
    last_name: "Obispo",
    email: "cobispo6@constantcontact.com",
    city: "Cabo Frio",
    street_address: "2 Washington Place",
    introduction:
      "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    mainImage: imagesArr[6],
    randomImage01: imagesArr[7],
    randomImage02: imagesArr[8],
    randomImage03: imagesArr[9],
    randomImage04: imagesArr[10],
    skills: getSkillsByIds([2, 3, 8, 9]),
  },
  {
    id: 8,
    nickname: "Molli",
    last_name: "Blenkinsopp",
    email: "mblenkinsopp7@google.ca",
    city: "Kalianyar Selatan",
    street_address: "4 Delladonna Drive",
    introduction:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    mainImage: imagesArr[7],
    randomImage01: imagesArr[8],
    randomImage02: imagesArr[9],
    randomImage03: imagesArr[10],
    randomImage04: imagesArr[11],
    skills: getSkillsByIds([5, 7, 8, 10]),
  },
  {
    id: 9,
    nickname: "Roseline",
    last_name: "Brann",
    email: "rbrann8@ucla.edu",
    city: "Chengnan",
    street_address: "51 Scofield Place",
    introduction:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    mainImage: imagesArr[8],
    randomImage01: imagesArr[9],
    randomImage02: imagesArr[10],
    randomImage03: imagesArr[11],
    randomImage04: imagesArr[12],
    skills: getSkillsByIds([2, 5, 7, 8]),
  },
  {
    id: 10,
    nickname: "Susie",
    last_name: "Vittore",
    email: "svittore9@uol.com.br",
    city: "Hennenman",
    street_address: "53 Lindbergh Terrace",
    introduction:
      "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    mainImage: imagesArr[9],
    randomImage01: imagesArr[10],
    randomImage02: imagesArr[11],
    randomImage03: imagesArr[12],
    randomImage04: imagesArr[13],
    skills: getSkillsByIds([4, 6, 7, 9]),
  },
  {
    id: 11,
    nickname: "Etienne",
    last_name: "Vaines",
    email: "evainesa@nytimes.com",
    city: "R S",
    street_address: "02598 Basil Trail",
    introduction:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    mainImage: imagesArr[10],
    randomImage01: imagesArr[11],
    randomImage02: imagesArr[12],
    randomImage03: imagesArr[13],
    randomImage04: imagesArr[14],
    skills: getSkillsByIds([2, 3, 4, 8]),
  },
  {
    id: 12,
    nickname: "Maxie",
    last_name: "Pinks",
    email: "mpinksb@paypal.com",
    city: "San Antonio",
    street_address: "1032 Myrtle Court",
    introduction:
      "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    mainImage: imagesArr[11],
    randomImage01: imagesArr[12],
    randomImage02: imagesArr[13],
    randomImage03: imagesArr[14],
    randomImage04: imagesArr[15],
    skills: getSkillsByIds([1, 6, 7, 9]),
  },
  {
    id: 13,
    nickname: "Chloris",
    last_name: "Lehr",
    email: "clehrc@blogtalkradio.com",
    city: "Napu",
    street_address: "73575 Lien Terrace",
    introduction:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    mainImage: imagesArr[12],
    randomImage01: imagesArr[13],
    randomImage02: imagesArr[14],
    randomImage03: imagesArr[15],
    randomImage04: imagesArr[16],
    skills: getSkillsByIds([5, 8, 9, 10]),
  },
  {
    id: 14,
    nickname: "Tiertza",
    last_name: "Francklyn",
    email: "tfrancklynd@ebay.co.uk",
    city: "San Justo",
    street_address: "9 Farmco Parkway",
    introduction:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    mainImage: imagesArr[13],
    randomImage01: imagesArr[14],
    randomImage02: imagesArr[15],
    randomImage03: imagesArr[16],
    randomImage04: imagesArr[17],
    skills: getSkillsByIds([3, 4, 5, 6]),
  },
  {
    id: 15,
    nickname: "Sondra",
    last_name: "Everill",
    email: "severille@about.com",
    city: "Plavy",
    street_address: "1 Village Green Hill",
    introduction:
      "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    mainImage: imagesArr[14],
    randomImage01: imagesArr[15],
    randomImage02: imagesArr[16],
    randomImage03: imagesArr[17],
    randomImage04: imagesArr[18],
    skills: getSkillsByIds([1, 2, 3, 4]),
  },
  {
    id: 16,
    nickname: "Vanya",
    last_name: "Caustick",
    email: "vcaustickf@go.com",
    city: "Pavlovskaya",
    street_address: "0 Vera Alley",
    introduction:
      "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    mainImage: imagesArr[15],
    randomImage01: imagesArr[16],
    randomImage02: imagesArr[17],
    randomImage03: imagesArr[18],
    randomImage04: imagesArr[19],
    skills: getSkillsByIds([3, 8, 9, 10]),
  },
  {
    id: 17,
    nickname: "Dalis",
    last_name: "Gunda",
    email: "dgundag@clickbank.net",
    city: "Łagów",
    street_address: "27 Spaight Point",
    introduction:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    mainImage: imagesArr[16],
    randomImage01: imagesArr[17],
    randomImage02: imagesArr[18],
    randomImage03: imagesArr[19],
    randomImage04: imagesArr[20],
    skills: getSkillsByIds([2, 3, 9, 10]),
  },
  {
    id: 18,
    nickname: "Sylvia",
    last_name: "Phippen",
    email: "sphippenh@cloudflare.com",
    city: "Pasembon",
    street_address: "8859 Miller Crossing",
    introduction:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    mainImage: imagesArr[17],
    randomImage01: imagesArr[18],
    randomImage02: imagesArr[19],
    randomImage03: imagesArr[20],
    randomImage04: imagesArr[21],
    skills: getSkillsByIds([1, 2, 5, 7]),
  },
  {
    id: 19,
    nickname: "Bernete",
    last_name: "Furneaux",
    email: "bfurneauxi@youku.com",
    city: "Pojok",
    street_address: "7 Sunfield Place",
    introduction:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    mainImage: imagesArr[18],
    randomImage01: imagesArr[19],
    randomImage02: imagesArr[20],
    randomImage03: imagesArr[21],
    randomImage04: imagesArr[22],
    skills: getSkillsByIds([5, 7, 8, 9]),
  },
  {
    id: 20,
    nickname: "Terrel",
    last_name: "Blaxton",
    email: "tblaxtonj@wordpress.com",
    city: "Deskle",
    street_address: "5 Declaration Avenue",
    introduction:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.",
    mainImage: imagesArr[19],
    randomImage01: imagesArr[20],
    randomImage02: imagesArr[21],
    randomImage03: imagesArr[22],
    randomImage04: imagesArr[23],
    skills: getSkillsByIds([4, 5, 6, 7]),
  },
  {
    id: 21,
    nickname: "Verile",
    last_name: "Georgi",
    email: "vgeorgik@1und1.de",
    city: "Laspezia",
    street_address: "3465 Walton Circle",
    introduction: "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
    mainImage: imagesArr[20],
    randomImage01: imagesArr[21],
    randomImage02: imagesArr[22],
    randomImage03: imagesArr[23],
    randomImage04: imagesArr[24],
    skills: getSkillsByIds([3, 4, 5, 6]),
  },
  {
    id: 22,
    nickname: "Hyacinthe",
    last_name: "Pietzker",
    email: "hpietzkerl@weather.com",
    city: "Predavac",
    street_address: "7386 Ridgeview Point",
    introduction:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    mainImage: imagesArr[21],
    randomImage01: imagesArr[22],
    randomImage02: imagesArr[23],
    randomImage03: imagesArr[24],
    randomImage04: imagesArr[25],
    skills: getSkillsByIds([6, 7, 8, 9]),
  },
  {
    id: 23,
    nickname: "Vernon",
    last_name: "Hovie",
    email: "vhoviem@feedburner.com",
    city: "Taraban Timur",
    street_address: "58086 Cambridge Pass",
    introduction:
      "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    mainImage: imagesArr[22],
    randomImage01: imagesArr[23],
    randomImage02: imagesArr[24],
    randomImage03: imagesArr[25],
    randomImage04: imagesArr[26],
    skills: getSkillsByIds([1, 7, 8, 9]),
  },
  {
    id: 24,
    nickname: "Kurtis",
    last_name: "Syne",
    email: "ksynen@ehow.com",
    city: "Nong Hin",
    street_address: "0425 Beilfuss Junction",
    introduction:
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    mainImage: imagesArr[23],
    randomImage01: imagesArr[24],
    randomImage02: imagesArr[25],
    randomImage03: imagesArr[26],
    randomImage04: imagesArr[27],
    skills: getSkillsByIds([3, 4, 7, 9]),
  },
  {
    id: 25,
    nickname: "Hermia",
    last_name: "Fraschini",
    email: "hfraschinio@deviantart.com",
    city: "Port Barton",
    street_address: "064 Loomis Alley",
    introduction:
      "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    mainImage: imagesArr[24],
    randomImage01: imagesArr[25],
    randomImage02: imagesArr[26],
    randomImage03: imagesArr[27],
    randomImage04: imagesArr[28],
    skills: getSkillsByIds([5, 6, 8, 10]),
  },
  {
    id: 26,
    nickname: "Nathaniel",
    last_name: "O'Shevlan",
    email: "noshevlanp@studiopress.com",
    city: "Cilegong",
    street_address: "1 Bunker Hill Pass",
    introduction:
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    mainImage: imagesArr[25],
    randomImage01: imagesArr[26],
    randomImage02: imagesArr[27],
    randomImage03: imagesArr[28],
    randomImage04: imagesArr[29],
    skills: getSkillsByIds([2, 6, 8, 10]),
  },
  {
    id: 27,
    nickname: "Bertie",
    last_name: "Drust",
    email: "bdrustq@myspace.com",
    city: "Wukou",
    street_address: "17543 Darwin Terrace",
    introduction:
      "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    mainImage: imagesArr[26],
    randomImage01: imagesArr[0],
    randomImage02: imagesArr[0],
    randomImage03: imagesArr[0],
    randomImage04: imagesArr[0],
    skills: getSkillsByIds([4, 7, 8, 9]),
  },
  {
    id: 28,
    nickname: "Kandace",
    last_name: "Mithun",
    email: "kmithunr@oakley.com",
    city: "Paratinga",
    street_address: "1902 Banding Road",
    introduction:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    mainImage: imagesArr[27],
    randomImage01: imagesArr[28],
    randomImage02: imagesArr[29],
    randomImage03: imagesArr[30],
    randomImage04: imagesArr[31],
    skills: getSkillsByIds([1, 7, 8, 9]),
  },
  {
    id: 29,
    nickname: "Adria",
    last_name: "Hamp",
    email: "ahamps@ftc.gov",
    city: "Paris 12",
    street_address: "03631 Cascade Junction",
    introduction:
      "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    mainImage: imagesArr[28],
    randomImage01: imagesArr[29],
    randomImage02: imagesArr[30],
    randomImage03: imagesArr[31],
    randomImage04: imagesArr[32],
    skills: getSkillsByIds([1, 2, 3, 4]),
  },
  {
    id: 30,
    nickname: "Prent",
    last_name: "Lehenmann",
    email: "plehenmannt@hud.gov",
    city: "Sanjinquan",
    street_address: "488 Claremont Drive",
    introduction:
      "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    mainImage: imagesArr[29],
    randomImage01: imagesArr[30],
    randomImage02: imagesArr[31],
    randomImage03: imagesArr[32],
    randomImage04: imagesArr[33],
    skills: getSkillsByIds([2, 5, 6, 7]),
  },
  {
    id: 31,
    nickname: "Christel",
    last_name: "De Domenicis",
    email: "cdedomenicisu@whitehouse.gov",
    city: "Wassa-Akropong",
    street_address: "0 Ryan Crossing",
    introduction:
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    mainImage: imagesArr[30],
    randomImage01: imagesArr[31],
    randomImage02: imagesArr[32],
    randomImage03: imagesArr[33],
    randomImage04: imagesArr[34],
    skills: getSkillsByIds([3, 6, 7, 10]),
  },
  {
    id: 32,
    nickname: "Carlynne",
    last_name: "Baud",
    email: "cbaudv@taobao.com",
    city: "Nova Lima",
    street_address: "82053 Dovetail Alley",
    introduction:
      "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    mainImage: imagesArr[31],
    randomImage01: imagesArr[32],
    randomImage02: imagesArr[33],
    randomImage03: imagesArr[34],
    randomImage04: imagesArr[35],
    skills: getSkillsByIds([2, 3, 6, 8]),
  },
  {
    id: 33,
    nickname: "Broddie",
    last_name: "Feaveer",
    email: "bfeaveerw@cbslocal.com",
    city: "Rantaupanjangkiri",
    street_address: "356 Sauthoff Trail",
    introduction: "Fusce consequat. Nulla nisl. Nunc nisl.",
    mainImage: imagesArr[32],
    randomImage01: imagesArr[33],
    randomImage02: imagesArr[34],
    randomImage03: imagesArr[35],
    randomImage04: imagesArr[36],
    skills: getSkillsByIds([3, 4, 5, 6]),
  },
  {
    id: 34,
    nickname: "Lexy",
    last_name: "Dellit",
    email: "ldellitx@apple.com",
    city: "Taokeng",
    street_address: "01247 Colorado Way",
    introduction:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    mainImage: imagesArr[33],
    randomImage01: imagesArr[34],
    randomImage02: imagesArr[35],
    randomImage03: imagesArr[36],
    randomImage04: imagesArr[37],
    skills: getSkillsByIds([2, 3, 7, 9]),
  },
  {
    id: 35,
    nickname: "Chastity",
    last_name: "Charley",
    email: "ccharleyy@i2i.jp",
    city: "Monte Francisco",
    street_address: "94089 Harbort Court",
    introduction:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    mainImage: imagesArr[34],
    randomImage01: imagesArr[35],
    randomImage02: imagesArr[36],
    randomImage03: imagesArr[37],
    randomImage04: imagesArr[38],
    skills: getSkillsByIds([1, 8, 9, 10]),
  },
  {
    id: 36,
    nickname: "Lesly",
    last_name: "Dupree",
    email: "ldupreez@github.com",
    city: "Firenze",
    street_address: "17531 Ryan Hill",
    introduction:
      "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    mainImage: imagesArr[35],
    randomImage01: imagesArr[36],
    randomImage02: imagesArr[37],
    randomImage03: imagesArr[38],
    randomImage04: imagesArr[39],
    skills: getSkillsByIds([5, 6, 7, 8]),
  },
  {
    id: 37,
    nickname: "Brandea",
    last_name: "Shipley",
    email: "bshipley10@hc360.com",
    city: "Wengtian",
    street_address: "91 Donald Park",
    introduction:
      "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    mainImage: imagesArr[36],
    randomImage01: imagesArr[37],
    randomImage02: imagesArr[38],
    randomImage03: imagesArr[39],
    randomImage04: imagesArr[40],
    skills: getSkillsByIds([2, 3, 4, 5]),
  },
  {
    id: 38,
    nickname: "Whitney",
    last_name: "Grierson",
    email: "wgrierson11@howstuffworks.com",
    city: "Walakeri",
    street_address: "4 Eagan Drive",
    introduction:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    mainImage: imagesArr[37],
    randomImage01: imagesArr[38],
    randomImage02: imagesArr[39],
    randomImage03: imagesArr[40],
    randomImage04: imagesArr[41],
    skills: getSkillsByIds([4, 7, 8, 9]),
  },
  {
    id: 39,
    nickname: "Randolf",
    last_name: "Albrook",
    email: "ralbrook12@smh.com.au",
    city: "Ibara",
    street_address: "65 Granby Parkway",
    introduction:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    mainImage: imagesArr[38],
    randomImage01: imagesArr[39],
    randomImage02: imagesArr[40],
    randomImage03: imagesArr[41],
    randomImage04: imagesArr[42],
    skills: getSkillsByIds([1, 2, 3, 4]),
  },
  {
    id: 40,
    nickname: "Ynez",
    last_name: "Fice",
    email: "yfice13@fotki.com",
    city: "Tianzhuang",
    street_address: "77444 Green Parkway",
    introduction:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    mainImage: imagesArr[39],
    randomImage01: imagesArr[40],
    randomImage02: imagesArr[41],
    randomImage03: imagesArr[42],
    randomImage04: imagesArr[43],
    skills: getSkillsByIds([1, 3, 5, 7]),
  },
  {
    id: 41,
    nickname: "Bentlee",
    last_name: "Rushmere",
    email: "brushmere14@home.pl",
    city: "Zliten",
    street_address: "599 Bowman Trail",
    introduction:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    mainImage: imagesArr[40],
    randomImage01: imagesArr[41],
    randomImage02: imagesArr[42],
    randomImage03: imagesArr[43],
    randomImage04: imagesArr[44],
    skills: getSkillsByIds([2, 3, 4, 10]),
  },
  {
    id: 42,
    nickname: "Caz",
    last_name: "Craythorn",
    email: "ccraythorn15@ed.gov",
    city: "Louisville",
    street_address: "0674 Thompson Parkway",
    introduction:
      "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    mainImage: imagesArr[41],
    randomImage01: imagesArr[42],
    randomImage02: imagesArr[43],
    randomImage03: imagesArr[44],
    randomImage04: imagesArr[45],
    skills: getSkillsByIds([6, 7, 8, 10]),
  },
  {
    id: 43,
    nickname: "Kareem",
    last_name: "Scapelhorn",
    email: "kscapelhorn16@slideshare.net",
    city: "Zitong",
    street_address: "1 Fordem Road",
    introduction: "Fusce consequat. Nulla nisl. Nunc nisl.",
    mainImage: imagesArr[42],
    randomImage01: imagesArr[43],
    randomImage02: imagesArr[44],
    randomImage03: imagesArr[45],
    randomImage04: imagesArr[46],
    skills: getSkillsByIds([4, 6, 7, 8]),
  },
  {
    id: 44,
    nickname: "Martelle",
    last_name: "Barti",
    email: "mbarti17@vistaprint.com",
    city: "Victoria",
    street_address: "7 Manitowish Avenue",
    introduction:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    mainImage: imagesArr[43],
    randomImage01: imagesArr[44],
    randomImage02: imagesArr[45],
    randomImage03: imagesArr[46],
    randomImage04: imagesArr[47],
    skills: getSkillsByIds([2, 5, 7, 10]),
  },
  {
    id: 45,
    nickname: "Karel",
    last_name: "Keat",
    email: "kkeat18@mtv.com",
    city: "Želešice",
    street_address: "4 Kennedy Center",
    introduction:
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    mainImage: imagesArr[44],
    randomImage01: imagesArr[45],
    randomImage02: imagesArr[46],
    randomImage03: imagesArr[47],
    randomImage04: imagesArr[48],
    skills: getSkillsByIds([1, 3, 4, 5]),
  },
  {
    id: 46,
    nickname: "Hercules",
    last_name: "Leeds",
    email: "hleeds19@eventbrite.com",
    city: "Bhāi Pheru",
    street_address: "401 Fisk Place",
    introduction:
      "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    mainImage: imagesArr[45],
    randomImage01: imagesArr[46],
    randomImage02: imagesArr[47],
    randomImage03: imagesArr[48],
    randomImage04: imagesArr[49],
    skills: getSkillsByIds([1, 2, 3, 4]),
  },
  {
    id: 47,
    nickname: "Bili",
    last_name: "Hallifax",
    email: "bhallifax1a@weibo.com",
    city: "Ad Darbāsīyah",
    street_address: "4 Bellgrove Road",
    introduction:
      "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    mainImage: imagesArr[46],
    randomImage01: imagesArr[47],
    randomImage02: imagesArr[48],
    randomImage03: imagesArr[49],
    randomImage04: imagesArr[50],
    skills: getSkillsByIds([2, 6, 8, 10]),
  },
  {
    id: 48,
    nickname: "Emile",
    last_name: "Wollaston",
    email: "ewollaston1b@narod.ru",
    city: "Castlerea",
    street_address: "7710 Northridge Park",
    introduction: "Sed ante. Vivamus tortor. Duis mattis egestas metus.",
    mainImage: imagesArr[47],
    randomImage01: imagesArr[48],
    randomImage02: imagesArr[49],
    randomImage03: imagesArr[50],
    randomImage04: imagesArr[51],
    skills: getSkillsByIds([3, 7, 8, 9]),
  },
  {
    id: 49,
    nickname: "Cherrita",
    last_name: "Need",
    email: "cneed1c@shareasale.com",
    city: "Balucuc",
    street_address: "99306 Florence Lane",
    introduction:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    mainImage: imagesArr[48],
    randomImage01: imagesArr[49],
    randomImage02: imagesArr[50],
    randomImage03: imagesArr[51],
    randomImage04: imagesArr[52],
    skills: getSkillsByIds([3, 4, 5, 7]),
  },
  {
    id: 50,
    nickname: "Caressa",
    last_name: "Jenken",
    email: "cjenken1d@auda.org.au",
    city: "Árgos",
    street_address: "4708 Hanson Center",
    introduction:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    mainImage: imagesArr[49],
    randomImage01: imagesArr[50],
    randomImage02: imagesArr[51],
    randomImage03: imagesArr[52],
    randomImage04: imagesArr[53],
    skills: getSkillsByIds([4, 5, 6, 10]),
  },
  {
    id: 51,
    nickname: "Joline",
    last_name: "Chardin",
    email: "jchardin1e@fotki.com",
    city: "Madimba",
    street_address: "57701 Homewood Circle",
    introduction:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    mainImage: imagesArr[50],
    randomImage01: imagesArr[51],
    randomImage02: imagesArr[52],
    randomImage03: imagesArr[53],
    randomImage04: imagesArr[54],
    skills: getSkillsByIds([7, 8, 9, 10]),
  },
  {
    id: 52,
    nickname: "Jeannine",
    last_name: "Bortolussi",
    email: "jbortolussi1f@symantec.com",
    city: "Rožďalovice",
    street_address: "422 Pepper Wood Terrace",
    introduction:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    mainImage: imagesArr[51],
    randomImage01: imagesArr[52],
    randomImage02: imagesArr[53],
    randomImage03: imagesArr[54],
    randomImage04: imagesArr[55],
    skills: getSkillsByIds([4, 5, 6, 10]),
  },
  {
    id: 53,
    nickname: "Demetre",
    last_name: "Letterese",
    email: "dletterese1g@devhub.com",
    city: "Marne-la-Vallée",
    street_address: "9 Oxford Pass",
    introduction:
      "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    mainImage: imagesArr[52],
    randomImage01: imagesArr[53],
    randomImage02: imagesArr[54],
    randomImage03: imagesArr[55],
    randomImage04: imagesArr[56],
    skills: getSkillsByIds([2, 3, 7, 9]),
  },
  {
    id: 54,
    nickname: "Doy",
    last_name: "Mintrim",
    email: "dmintrim1h@dion.ne.jp",
    city: "James Craik",
    street_address: "6352 Swallow Parkway",
    introduction:
      "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    mainImage: imagesArr[53],
    randomImage01: imagesArr[54],
    randomImage02: imagesArr[55],
    randomImage03: imagesArr[56],
    randomImage04: imagesArr[57],
    skills: getSkillsByIds([3, 4, 6, 10]),
  },
  {
    id: 55,
    nickname: "Lurette",
    last_name: "Simonson",
    email: "lsimonson1i@blinklist.com",
    city: "Dayu",
    street_address: "2070 Tennessee Parkway",
    introduction:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    mainImage: imagesArr[54],
    randomImage01: imagesArr[55],
    randomImage02: imagesArr[56],
    randomImage03: imagesArr[57],
    randomImage04: imagesArr[58],
    skills: getSkillsByIds([4, 5, 8, 9]),
  },
  {
    id: 56,
    nickname: "Jules",
    last_name: "Tuffley",
    email: "jtuffley1j@omniture.com",
    city: "Arauca",
    street_address: "50886 Moulton Terrace",
    introduction:
      "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    mainImage: imagesArr[55],
    randomImage01: imagesArr[56],
    randomImage02: imagesArr[57],
    randomImage03: imagesArr[58],
    randomImage04: imagesArr[59],
    skills: getSkillsByIds([1, 4, 5, 7]),
  },
  {
    id: 57,
    nickname: "Isadora",
    last_name: "Whiff",
    email: "iwhiff1k@ucsd.edu",
    city: "Davyd-Haradok",
    street_address: "46 Burrows Terrace",
    introduction:
      "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
    mainImage: imagesArr[56],
    randomImage01: imagesArr[57],
    randomImage02: imagesArr[58],
    randomImage03: imagesArr[59],
    randomImage04: imagesArr[60],
    skills: getSkillsByIds([2, 4, 5, 6]),
  },
  {
    id: 58,
    nickname: "Nari",
    last_name: "Matveichev",
    email: "nmatveichev1l@artisteer.com",
    city: "Jaunpiebalga",
    street_address: "55273 Shasta Park",
    introduction:
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    mainImage: imagesArr[57],
    randomImage01: imagesArr[58],
    randomImage02: imagesArr[59],
    randomImage03: imagesArr[60],
    randomImage04: imagesArr[61],
    skills: getSkillsByIds([5, 6, 7, 8]),
  },
  {
    id: 59,
    nickname: "Valentine",
    last_name: "Itzkovitch",
    email: "vitzkovitch1m@yolasite.com",
    city: "Xinning",
    street_address: "536 Ramsey Hill",
    introduction: "Sed ante. Vivamus tortor. Duis mattis egestas metus.",
    mainImage: imagesArr[58],
    randomImage01: imagesArr[59],
    randomImage02: imagesArr[60],
    randomImage03: imagesArr[61],
    randomImage04: imagesArr[62],
    skills: getSkillsByIds([1, 6, 7, 10]),
  },
  {
    id: 60,
    nickname: "Rita",
    last_name: "Brinkley",
    email: "rbrinkley1n@hubpages.com",
    city: "Zmiennica",
    street_address: "1893 Coleman Plaza",
    introduction:
      "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    mainImage: imagesArr[59],
    randomImage01: imagesArr[60],
    randomImage02: imagesArr[61],
    randomImage03: imagesArr[62],
    randomImage04: imagesArr[63],
    skills: getSkillsByIds([2, 5, 8, 10]),
  },
  {
    id: 61,
    nickname: "Ashlan",
    last_name: "Arondel",
    email: "aarondel1o@guardian.co.uk",
    city: "Västerås",
    street_address: "7557 Drewry Place",
    introduction:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    mainImage: imagesArr[60],
    randomImage01: imagesArr[61],
    randomImage02: imagesArr[62],
    randomImage03: imagesArr[63],
    randomImage04: imagesArr[64],
    skills: getSkillsByIds([4, 6, 8, 9]),
  },
  {
    id: 62,
    nickname: "Neville",
    last_name: "Von Der Empten",
    email: "nvonderempten1p@spiegel.de",
    city: "Zyablikovo",
    street_address: "60 Milwaukee Circle",
    introduction:
      "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    mainImage: imagesArr[61],
    randomImage01: imagesArr[62],
    randomImage02: imagesArr[63],
    randomImage03: imagesArr[64],
    randomImage04: imagesArr[65],
    skills: getSkillsByIds([3, 4, 5, 8]),
  },
  {
    id: 63,
    nickname: "Bobine",
    last_name: "Rantoull",
    email: "brantoull1q@yolasite.com",
    city: "Solna",
    street_address: "8 Alpine Alley",
    introduction:
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    mainImage: imagesArr[62],
    randomImage01: imagesArr[63],
    randomImage02: imagesArr[64],
    randomImage03: imagesArr[65],
    randomImage04: imagesArr[66],
    skills: getSkillsByIds([2, 5, 7, 8]),
  },
  {
    id: 64,
    nickname: "Anatollo",
    last_name: "Branson",
    email: "abranson1r@ask.com",
    city: "Had Kourt",
    street_address: "0 Magdeline Place",
    introduction: "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
    mainImage: imagesArr[63],
    randomImage01: imagesArr[64],
    randomImage02: imagesArr[65],
    randomImage03: imagesArr[66],
    randomImage04: imagesArr[67],
    skills: getSkillsByIds([4, 5, 7, 8]),
  },
  {
    id: 65,
    nickname: "Bianka",
    last_name: "Buesden",
    email: "bbuesden1s@technorati.com",
    city: "El Limon",
    street_address: "38 Trailsway Park",
    introduction:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    mainImage: imagesArr[64],
    randomImage01: imagesArr[65],
    randomImage02: imagesArr[66],
    randomImage03: imagesArr[67],
    randomImage04: imagesArr[68],
    skills: getSkillsByIds([2, 6, 7, 8]),
  },
  {
    id: 66,
    nickname: "Leelah",
    last_name: "Harbach",
    email: "lharbach1t@omniture.com",
    city: "Batiano",
    street_address: "28 Bellgrove Street",
    introduction:
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    mainImage: imagesArr[65],
    randomImage01: imagesArr[66],
    randomImage02: imagesArr[67],
    randomImage03: imagesArr[68],
    randomImage04: imagesArr[69],
    skills: getSkillsByIds([5, 7, 8, 9]),
  },
  {
    id: 67,
    nickname: "Emylee",
    last_name: "Sundin",
    email: "esundin1u@bluehost.com",
    city: "Biito",
    street_address: "795 Derek Avenue",
    introduction:
      "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    mainImage: imagesArr[66],
    randomImage01: imagesArr[67],
    randomImage02: imagesArr[68],
    randomImage03: imagesArr[69],
    randomImage04: imagesArr[0],
    skills: getSkillsByIds([3, 6, 8, 9]),
  },
  {
    id: 68,
    nickname: "Ole",
    last_name: "Sanders",
    email: "osanders1v@dmoz.org",
    city: "G‘azalkent",
    street_address: "73027 Dunning Plaza",
    introduction:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    mainImage: imagesArr[67],
    randomImage01: imagesArr[68],
    randomImage02: imagesArr[69],
    randomImage03: imagesArr[0],
    randomImage04: imagesArr[1],
    skills: getSkillsByIds([5, 6, 9, 10]),
  },
  {
    id: 69,
    nickname: "Ivie",
    last_name: "Frizell",
    email: "ifrizell1w@vk.com",
    city: "Nunutba",
    street_address: "0246 Browning Point",
    introduction:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    mainImage: imagesArr[68],
    randomImage01: imagesArr[69],
    randomImage02: imagesArr[0],
    randomImage03: imagesArr[1],
    randomImage04: imagesArr[2],
    skills: getSkillsByIds([1, 2, 3, 7]),
  },
  {
    id: 70,
    nickname: "Travis",
    last_name: "Brannigan",
    email: "tbrannigan1x@marriott.com",
    city: "Shiguai",
    street_address: "05 Crowley Junction",
    introduction:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    mainImage: imagesArr[69],
    randomImage01: imagesArr[0],
    randomImage02: imagesArr[1],
    randomImage03: imagesArr[2],
    randomImage04: imagesArr[3],
    skills: getSkillsByIds([6, 7, 9, 10]),
  },
];
